import { RoadCorridor, RoadReportData } from '../types';

export const INITIAL_CORRIDORS: RoadCorridor[] = [
  {
    id: 'corridor-nh10',
    code: 'NH-10',
    name: 'Siliguri — Gangtok Lifeline',
    state: 'Sikkim',
    districts: ['Kalimpong', 'Pakyong', 'Gangtok'],
    currentStatus: 'blocked',
    primaryHazard: 'landslide',
    lastReportedAt: Date.now() - 1000 * 60 * 25, // 25 mins ago
    activeReportsCount: 4,
    lengthKm: 114,
    criticalPoints: [
      { name: '29th Mile (Sevoke-Teesta)', lat: 26.9842, lng: 88.4612, status: 'blocked', hazard: 'landslide' },
      { name: 'Setijhora Bridge Section', lat: 26.9215, lng: 88.4418, status: 'risky', hazard: 'mudslide' },
      { name: 'Singtam Junction', lat: 27.2341, lng: 88.4975, status: 'open', hazard: 'clear' },
      { name: 'Ranipool Outskirts', lat: 27.2912, lng: 88.5912, status: 'open', hazard: 'clear' },
    ],
  },
  {
    id: 'corridor-nh27',
    code: 'NH-27',
    name: 'Guwahati — Dima Hasao — Silchar',
    state: 'Assam',
    districts: ['Kamrup Metro', 'Hojai', 'Dima Hasao', 'Cachar'],
    currentStatus: 'risky',
    primaryHazard: 'mudslide',
    lastReportedAt: Date.now() - 1000 * 60 * 42,
    activeReportsCount: 6,
    lengthKm: 340,
    criticalPoints: [
      { name: 'Jatinga Valley (Haflong)', lat: 25.1215, lng: 93.0315, status: 'risky', hazard: 'mudslide' },
      { name: 'New Harangajao Cutting', lat: 25.0412, lng: 92.8911, status: 'blocked', hazard: 'rockfall' },
      { name: 'Silchar Bypass Bridge', lat: 24.8333, lng: 92.7789, status: 'open', hazard: 'clear' },
    ],
  },
  {
    id: 'corridor-nh6',
    code: 'NH-6',
    name: 'Shillong — Jowai — Ratacherra',
    state: 'Meghalaya',
    districts: ['East Khasi Hills', 'West Jaintia Hills', 'East Jaintia Hills'],
    currentStatus: 'blocked',
    primaryHazard: 'subsidence',
    lastReportedAt: Date.now() - 1000 * 60 * 15,
    activeReportsCount: 5,
    lengthKm: 210,
    criticalPoints: [
      { name: 'Sonapur Tunnel Approach', lat: 25.0841, lng: 92.3512, status: 'blocked', hazard: 'mudslide' },
      { name: 'Khliehriat Coal Basin Road', lat: 25.3521, lng: 92.3681, status: 'risky', hazard: 'subsidence' },
      { name: 'Umiam Lake Viaduct', lat: 25.6542, lng: 91.8974, status: 'open', hazard: 'clear' },
    ],
  },
  {
    id: 'corridor-nh29',
    code: 'NH-29',
    name: 'Dimapur — Kohima Express Corridor',
    state: 'Nagaland',
    districts: ['Dimapur', 'Chumukedima', 'Kohima'],
    currentStatus: 'risky',
    primaryHazard: 'rockfall',
    lastReportedAt: Date.now() - 1000 * 60 * 70,
    activeReportsCount: 3,
    lengthKm: 74,
    criticalPoints: [
      { name: 'Pagla Pahar Gorge', lat: 25.7915, lng: 93.7654, status: 'risky', hazard: 'rockfall' },
      { name: 'Old KMC Dumping Area', lat: 25.6812, lng: 94.0845, status: 'blocked', hazard: 'landslide' },
      { name: 'Zubza Overbridge', lat: 25.7123, lng: 94.0211, status: 'open', hazard: 'clear' },
    ],
  },
  {
    id: 'corridor-nh13',
    code: 'NH-13',
    name: 'Trans-Arunachal Highway (Potin-Pangin)',
    state: 'Arunachal Pradesh',
    districts: ['Papum Pare', 'Lower Subansiri', 'Siang'],
    currentStatus: 'blocked',
    primaryHazard: 'flash_flood',
    lastReportedAt: Date.now() - 1000 * 60 * 95,
    activeReportsCount: 4,
    lengthKm: 420,
    criticalPoints: [
      { name: 'Kala Matti Rock Face', lat: 27.2412, lng: 93.7214, status: 'blocked', hazard: 'landslide' },
      { name: 'Subansiri Bailey Bridge', lat: 27.8124, lng: 94.2145, status: 'risky', hazard: 'flash_flood' },
      { name: 'Yupia Road Junction', lat: 27.1512, lng: 93.6812, status: 'open', hazard: 'clear' },
    ],
  },
  {
    id: 'corridor-nh306',
    code: 'NH-306',
    name: 'Silchar — Kolasib — Aizawl Lifeline',
    state: 'Mizoram',
    districts: ['Kolasib', 'Aizawl'],
    currentStatus: 'risky',
    primaryHazard: 'subsidence',
    lastReportedAt: Date.now() - 1000 * 60 * 120,
    activeReportsCount: 2,
    lengthKm: 130,
    criticalPoints: [
      { name: 'Vairengte Border Checkpoint', lat: 24.5123, lng: 92.7612, status: 'open', hazard: 'clear' },
      { name: 'Kolasib Hill Cut', lat: 24.2215, lng: 92.6812, status: 'risky', hazard: 'subsidence' },
      { name: 'Sairang River Bridge', lat: 23.8112, lng: 92.6512, status: 'open', hazard: 'clear' },
    ],
  },
  {
    id: 'corridor-nh102',
    code: 'NH-102',
    name: 'Imphal — Tengnoupal — Moreh',
    state: 'Manipur',
    districts: ['Imphal West', 'Thoubal', 'Tengnoupal'],
    currentStatus: 'open',
    primaryHazard: 'waterlogging',
    lastReportedAt: Date.now() - 1000 * 60 * 180,
    activeReportsCount: 1,
    lengthKm: 107,
    criticalPoints: [
      { name: 'Tengnoupal Ridge', lat: 24.3812, lng: 94.1412, status: 'open', hazard: 'waterlogging' },
      { name: 'Kakching Lamkhai', lat: 24.5112, lng: 93.9812, status: 'open', hazard: 'clear' },
    ],
  },
  {
    id: 'corridor-nh8',
    code: 'NH-8',
    name: 'Agartala — Teliamura — Churaibari',
    state: 'Tripura',
    districts: ['West Tripura', 'Khowai', 'North Tripura'],
    currentStatus: 'open',
    primaryHazard: 'clear',
    lastReportedAt: Date.now() - 1000 * 60 * 240,
    activeReportsCount: 0,
    lengthKm: 198,
    criticalPoints: [
      { name: 'Baramura Hill Pass', lat: 23.8812, lng: 91.5612, status: 'open', hazard: 'clear' },
      { name: 'Manu River Bridge', lat: 23.9912, lng: 92.0123, status: 'open', hazard: 'clear' },
    ],
  },
];

export const SEED_REPORTS: RoadReportData[] = [
  {
    id: 'rep-seed-1',
    corridorId: 'corridor-nh10',
    roadName: 'NH-10 Siliguri-Gangtok',
    state: 'Sikkim',
    district: 'Kalimpong',
    status: 'blocked',
    hazardType: 'landslide',
    description: 'Heavy boulders collapsed at 29th Mile after overnight cloudburst. BRO Task Force 63 bulldozers deployed. Both lanes impassable for commercial freight.',
    latitude: 26.9842,
    longitude: 88.4612,
    userRole: 'bro_official',
    reporterName: 'Subedar R. Thapa (BRO)',
    timestamp: Date.now() - 1000 * 60 * 28,
    version: 3,
    syncState: 'synced',
    confirmations: 19,
    photoUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'rep-seed-2',
    corridorId: 'corridor-nh6',
    roadName: 'NH-6 Shillong-Jowai',
    state: 'Meghalaya',
    district: 'East Jaintia Hills',
    status: 'blocked',
    hazardType: 'mudslide',
    description: 'Mudflow near Sonapur tunnel mouth blocking heavy vehicle passage. Light vehicles taking treacherous diversion via old bypass.',
    latitude: 25.0841,
    longitude: 92.3512,
    userRole: 'fleet_operator',
    reporterName: 'Maruti Logistics Dispatch',
    timestamp: Date.now() - 1000 * 60 * 55,
    version: 2,
    syncState: 'synced',
    confirmations: 14,
    photoUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'rep-seed-3',
    corridorId: 'corridor-nh27',
    roadName: 'NH-27 Guwahati-Silchar',
    state: 'Assam',
    district: 'Dima Hasao',
    status: 'risky',
    hazardType: 'mudslide',
    description: 'Single-lane traffic operating at Jatinga valley due to continuous seepage and soft soil sliding. Slow moving convoy.',
    latitude: 25.1215,
    longitude: 93.0315,
    userRole: 'commercial_driver',
    reporterName: 'Bikram Gogoi (Truck #AS01-GC-4482)',
    timestamp: Date.now() - 1000 * 60 * 90,
    version: 1,
    syncState: 'synced',
    confirmations: 8,
  },
  {
    id: 'rep-seed-4',
    corridorId: 'corridor-nh29',
    roadName: 'NH-29 Dimapur-Kohima',
    state: 'Nagaland',
    district: 'Chumukedima',
    status: 'risky',
    hazardType: 'rockfall',
    description: 'Intermittent rock falls at Pagla Pahar stretch. Traffic police regulating vehicles in one-way batches every 20 minutes.',
    latitude: 25.7915,
    longitude: 93.7654,
    userRole: 'emergency_responder',
    reporterName: 'Nagaland Traffic Control #3',
    timestamp: Date.now() - 1000 * 60 * 140,
    version: 2,
    syncState: 'synced',
    confirmations: 12,
  },
  {
    id: 'rep-seed-5',
    corridorId: 'corridor-nh13',
    roadName: 'NH-13 Trans-Arunachal',
    state: 'Arunachal Pradesh',
    district: 'Lower Subansiri',
    status: 'blocked',
    hazardType: 'flash_flood',
    description: 'River water overflowing Bailey bridge by 1.5 feet following flash flood. Bridge closed until water recedes.',
    latitude: 27.8124,
    longitude: 94.2145,
    userRole: 'resident',
    reporterName: 'Tage Duyu',
    timestamp: Date.now() - 1000 * 60 * 210,
    version: 1,
    syncState: 'synced',
    confirmations: 24,
  },
];
